load("@rules_cc//cc:defs.bzl", "cc_binary","cc_library")

cc_library(
    name = "hello1",
    srcs = ["hello1.c"],
    hdrs = ["hello1.h"],
)
cc_library(
    name = "hello2",
    srcs = ["hello2.c"],
    hdrs = ["hello2.h"],
)
cc_library(
    name = "hello3",
    srcs = ["hello3.c"],
    hdrs = ["hello3.h"],
)
cc_library(
    name = "hello4",
    srcs = ["hello4.c"],
    hdrs = ["hello4.h"],
)
cc_library(
    name = "hello5",
    srcs = ["hello5.c"],
    hdrs = ["hello5.h"],
)
cc_library(
    name = "hello6",
    srcs = ["hello6.c"],
    hdrs = ["hello6.h"],
)
cc_library(
    name = "hello7",
    srcs = ["hello7.c"],
    hdrs = ["hello7.h"],
)
cc_library(
    name = "hello8",
    srcs = ["hello8.c"],
    hdrs = ["hello8.h"],
)
cc_library(
    name = "hello9",
    srcs = ["hello9.c"],
    hdrs = ["hello9.h"],
)
cc_library(
    name = "hello10",
    srcs = ["hello10.c"],
    hdrs = ["hello10.h"],
)
cc_binary(
    name = "main",
    srcs = ["main.c"],
     deps = [
        "hello1",
        "hello2",
        "hello3",
        "hello4",
        "hello5",
        "hello6",
        "hello7",
        "hello8",
        "hello9",
        "hello10",
    ],
)